/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "idle1.h"

double get_idle();
void
idle2_3(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	entry  register1_3_arg;
	entry  *result_2;
	entry  find_max_3_arg;
	double x;
	int ch=-1;
#ifndef	DEBUG
	
	clnt = clnt_create (host, idle2, idle3, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	//printf("fgfasg\n");
#endif	/* DEBUG */
/*
	result_1 = register1_3(&register1_3_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = find_max_3(&find_max_3_arg, clnt);
	if (result_2 == (entry *) NULL) {
		clnt_perror (clnt, "call failed");
	}*/

	while(ch!=0)
	{
		printf("Enter the choice\n1.Register\n2.Get max\n0.Exit \n");
		scanf("%d",&ch);
		
		switch(ch)
		{
			case 1:
				strcpy(register1_3_arg.IP,host);
				x=get_idle();
				register1_3_arg.perc=x;
				result_1 = register1_3(&register1_3_arg, clnt);
				printf("\nSuccessfully registered\n");				
				break;
			
			case 2:
				result_2=find_max_3(&find_max_3_arg,clnt);
				printf("\nIP is %s and its maximum perc = %lf ",result_2->IP,result_2->perc);
				break;
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

double get_idle()
{
	char temp[30][5];
	char buffer[100];
	double array[20];
	FILE *fp;
	system("mpstat | grep all > abc.txt");
	fp=fopen("abc.txt","r");
	fgets(buffer,100,fp);
	printf("\nThe output of mpstat is::\n%s",buffer);
	sscanf(buffer,"%s%s%s%lf%lf%lf%lf%lf%lf%lf%lf%lf%lf",temp[0],temp[1],temp[2],&array[0],&array[1],&array[2],&array[3],&array[4],&array	[5],&array[6],&array[7],&array[8],&array[9]);
	//printf("%lf",array[9]);
	//return (double)array[9];
	return array[9];
}


int
main (int argc, char *argv[])
{
	char *host;
	//int ch;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	idle2_3 (host);
exit (0);
}
