/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "idle1.h"
struct entry list[10];
int cnt=0;

void *
register1_3_svc(entry *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	int i;
	strcpy(list[cnt].IP,argp->IP);
	list[cnt].perc=argp->perc;	
	cnt++;
	printf("=====registry=====\n");
	for(i=0;i<cnt;i++)
	{
		printf("IP=%s and Idle perce = %lf\n",list[i].IP,list[i].perc);
	}


	return (void *) &result;
}

entry *
find_max_3_svc(entry *argp, struct svc_req *rqstp)
{
	static entry  result;

	/*
	 * insert server code here
	 */int i,j;
	double max=0.0;
	/*
	 * insert server code here
	 */
	for(i=0;i<cnt;i++)
	{
		if(list[i].perc>max)
		{
			max=list[i].perc;
			j=i;
		}
	}
	return &list[j];

	
}
