/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sum.h"


void
sum_1(char *host)
{
	CLIENT *clnt;
	int  *result;
	param  arg;

#ifndef	DEBUG
	clnt = clnt_create (host, sum, sum_ver, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	arg.num1=4;
	arg.num2=5;
	result= addition_1(&arg, clnt);
	
	if (result == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("%d",*result);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	sum_1 (host);
exit (0);
}
